modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="fastergravel"
version="${file.jarVersion}"
displayName="Run faster on gravel blocks"
authors="DahakaMVl"
description='''
Run faster on gravel blocks.
'''